### ISSUE TITLE
Frage zur Klasse Student

### ISSUE THREAD

**Issue by magutma** [magutma/SoftwareentwicklungII#1]
Aufgabe:
Die Klasse Student erweitert die Klasse Person. Zusätzlich enthält Sie die Matrikelnummer
als int mit einem Getter getMatrikel. Die Klasse soll die Matrikelnummer im
Konstruktor als fortlaufende Nummer beginnend mit 1000000 vergeben. Verwenden Sie
dazu eine private Klassenvariable und eine private statische Methode. Nutzen Sie im
Konstruktor den Aufruf des Konstruktors von Person.
Frage:
Wie kann genau erzeuge ich die Matrikelnummern in der statischen Methode und übergebe sie dann dem Konstruktor?

**Comment by AndreasGeyer** [comment]
Du brauchst eine statische Variable nextMatrikelnummer. Statische Variablen sind nicht an Objekte gebunden, sondern für die gesamte Klasse zugänglich. In dem Fall will ja nicht ein einzelnes Objekt die nächsthöhere Matrikelnummer kennen, sondern die Klasse.

`private static int nextMatrikelnummer = 1000000;`

Anschließend setzt du die Matrikelnummer nur noch im Konstruktor und addierst 1 zu dem Wert. Das könnte man auch in einer statischen Methode machen

```
Student (String name){
    super(name);
    // neuer Code
    this.matrikelnummer = Student.nextMatrikelnummer;
    Student.nextMatrikelnummer++;
}
```

Auf statische Attribute wird immer folgendermaßen zugegriffen:
_Klassenname_._Attirbut/Methode_

An den Konstruktor der Klasse Person, kannst du das nicht übergeben, weil eine Person keine Matrikelnummer hat.

> Nutzen Sie im
Konstruktor den Aufruf des Konstruktors von Person.

--> Ist bereits durch Aufruf von **super(name);** implementiert.

**Comment by magutma** [comment]
hat geklappt:)
