### ISSUE TITLE
Frage zur Klasse WrittenExam: 

### ISSUE THREAD

**Issue by magutma** [magutma/SoftwareentwicklungII#2]
Die Klasse WrittenExam implementiert das Interface Exam. Implementieren Sie die
dazu notwendigen Getter und die dazugehörigen Objektvariablen. In getExamRooms
und getStudents erzeugen Sie jeweils ein neues HashSet aus dem Wert der jeweiligen
Objektvariable und geben dieses zurück. Andernfalls könnte ein Aufrufer die in der
Objektvariable gespeicherte Menge verändern

Weißt du was er damit will?

In getExamRooms
und getStudents erzeugen Sie jeweils ein neues HashSet aus dem Wert der jeweiligen
Objektvariable und geben dieses zurück.

**Comment by AndreasGeyer** [comment]
Du hast ja schon diene Variable RoomSet;
Dann muss deine Funktion so aussehen:

@Override
```
public Set<Room> getExamRooms() {
    HashSet<Room> rooms = new HashSet<Room>();
    for(Room r: RoomSet){
        rooms.add(r);
    }
    return rooms;
}
```

Gewöhn dir auch gleich an richtig zu programmieren.
Variablen immer an den Anfang von Klassen, dann Konstruktor, dann Methoden.
Variablen immer CamelCase (klein beginnen).

**Comment by magutma** [comment]
ah okay. Dann zeigt er mir aber trotzdem noch beim Test: WrittenExamTest.addAndRemoveExamRooms folgende Meldung:
 
java.lang.AssertionError: 
Expected :[ExamRoom@8eb587f6]
Actual   :[ExamRoom@8eb587f8]

Weißt du was da falsch ist?
